AllCops:
  NewCops: enable

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Style/TrailingCommaInHashLiteral:
  Enabled: false

Layout/LineLength:
  Max: 150

Metrics/MethodLength:
  Max: 500

Metrics/ClassLength:
  Max: 500

Metrics/BlockLength:
  Max: 100

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Style/SoleNestedConditional:
  Enabled: false
